# Generated by Django 3.0 on 2020-08-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us_county', '0003_auto_20200819_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCountyMeasures',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('cases', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('us_county', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uscountymeasures_relation', to='us_county.USCounty')),
            ],
            options={
                'verbose_name': 'us county measures',
                'verbose_name_plural': 'us county measuress',
                'db_table': 'covid19_us_county_measures',
                'ordering': ['-date'],
                'abstract': False,
                'unique_together': {('us_county', 'date')},
            },
        ),
    ]
