# Generated by Django 3.0 on 2020-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USCounty',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('full_name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'us county',
                'verbose_name_plural': 'us counties',
                'db_table': 'covid19_us_county',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
