# Generated by Django 3.0 on 2020-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_county', '0003_auto_20200819_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscounty',
            name='fips',
            field=models.IntegerField(max_length=256, null=True),
        ),
    ]
