# Generated by Django 3.0 on 2020-08-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_state', '0002_auto_20200819_0457'),
        ('us_state_measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usstatemeasures',
            options={'ordering': ['-date'], 'verbose_name': 'us state measures', 'verbose_name_plural': 'us state measuress'},
        ),
        migrations.AlterUniqueTogether(
            name='usstatemeasures',
            unique_together={('us_state', 'date')},
        ),
        migrations.RemoveField(
            model_name='usstatemeasures',
            name='name',
        ),
    ]
